/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Connect.DBManager;
import Controler.Reports;
import DML.Inserts;
import Model_Object.CreateOrder;
import Model_Object.UserCompany;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Michal
 */
public class OrderNew extends javax.swing.JFrame {

    private static DBManager DbManager;
    private static TableModel tableModel;
    private DefaultTableModel modelShopBag;
    private Reports Report;
    private static UserCompany User;
    private Object[] o;
    private double totalPrice = 0.0;

    /**
     * Creates new form OrderNew
     */
    public OrderNew(DBManager dbManager, UserCompany user) {
        this.DbManager = dbManager;
        this.User = user;
        initComponents();
        jlTotalPrice.setText(totalPrice + " €");
        jLabelFinalPrice.setText(totalPrice + " €");
        jLabelDiscoutPricce.setText(0 + " €");
        this.Report = new Reports(dbManager);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tableModel = jTableMyOrderItem.getModel();
        modelShopBag = (DefaultTableModel) jTableMyOrderItem.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMyOrderItem = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTextDicoutCode = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelFinalPrice = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jlTotalPrice = new javax.swing.JLabel();
        jLabelPrice2 = new javax.swing.JLabel();
        jLabelDiscoutPricce = new javax.swing.JLabel();
        jButtonShow = new javax.swing.JButton();
        jButtonShow1 = new javax.swing.JButton();
        jButtonAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("New order"));

        jLabel22.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel22.setText("Number order:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTableMyOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of product", "Brand", "Discount", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTableMyOrderItem);

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel24.setText("Discout code: ");

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelFinalPrice.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel28.setText("Final price: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabelFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFinalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel26.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel26.setText("Price:");

        jlTotalPrice.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N

        jLabelPrice2.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabelPrice2.setText("Discount price:");

        jLabelDiscoutPricce.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N

        jButtonShow.setBackground(new java.awt.Color(102, 102, 102));
        jButtonShow.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jButtonShow.setText("Apply");
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jButtonShow1.setBackground(new java.awt.Color(102, 102, 102));
        jButtonShow1.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jButtonShow1.setText("Delete product");
        jButtonShow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShow1ActionPerformed(evt);
            }
        });

        jButtonAll.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAll.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jButtonAll.setText("Confirm order");
        jButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jlTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPrice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDiscoutPricce, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextDicoutCode, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addComponent(jButtonShow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButtonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextDicoutCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonShow)))
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDiscoutPricce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        String code = jTextDicoutCode.getText().trim();
        String email = User.getEmailLog();
        int user_id = Report.getUserId(email);
        double perDis = 0.0;
        double cenDis = 0.0;
        try {

            boolean per = Report.getPerCenDiscount(user_id, code);

            if (per) {
                {
                    double perValue = 0.0;
                    perDis = Report.getPerDis(user_id, code);
//                    System.out.println("percentualna " + perDis);
                    
                     perValue = totalPrice * (perDis/100);
                     totalPrice = totalPrice - perValue;
                     jLabelFinalPrice.setText(totalPrice + " €");
                     jLabelDiscoutPricce.setText(perDis + " %");
                }
            } else {
                cenDis = Report.getCenDis(user_id, code);
//                System.out.println("cenova " + cenDis);
                if (totalPrice > cenDis) {
                    totalPrice = totalPrice - cenDis;
                    jLabelFinalPrice.setText(totalPrice + " €");
                    jLabelDiscoutPricce.setText(cenDis + " €");
                } else {
                    JOptionPane.showMessageDialog(null, "Minimum price must be higher than discount", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderNew.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonShowActionPerformed

    private void jButtonShow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShow1ActionPerformed
     if (jTableMyOrderItem.getSelectedRow() != -1) {
        int selectRow = jTableMyOrderItem.getSelectedRow();
        modelShopBag.removeRow(selectRow);
        
        setTotalPrice();
        } else {
            JOptionPane.showMessageDialog(null, "Choose some product ", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        

    }//GEN-LAST:event_jButtonShow1ActionPerformed

    public void setTotalPrice() {
        double price = 0.0;
        for (int i = 0; i < modelShopBag.getRowCount(); i++) {
            price += (double) modelShopBag.getValueAt(i, 3);
        }
        totalPrice = price;
        jlTotalPrice.setText(totalPrice + " €");
        jLabelFinalPrice.setText(totalPrice + " €");

    }

    public double getTotalPrice() {
        return totalPrice;
    }

    private void jButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllActionPerformed
        Inserts DataManager = new Inserts(DbManager);
        Reports report = new Reports(DbManager);
        String code = jTextDicoutCode.getText().trim();
        String email = User.getEmailLog();
        int user_id = Report.getUserId(email);
        double perDis = 0.0;
        double cenDis = 0.0;
        boolean per;
         if(jTableMyOrderItem.getRowCount() > 0){
            CreateOrder order = new CreateOrder(new Date(),4,user_id,"S");
            DataManager.insertOrder(order);
        try {
            per = Report.getPerCenDiscount(user_id, code);
             int IdOrder = report.getMaxIdOrder();
            for (int i = 0; i < modelShopBag.getRowCount(); i++) {
            String nazov = (String) modelShopBag.getValueAt(i, 0);
            double price = (Double) modelShopBag.getValueAt(i, 3);
            int IdProduct = report.getIDProduct(nazov);
            int IdDiscout = report.getIdDiscout(code);
            
            if (per) {
                {
                    perDis = Report.getPerDis(user_id, code);
                    
                    price = price * ((100-perDis)/100);
                    DataManager.insertProduct(IdProduct, IdDiscout, IdOrder, price);
                    DataManager.updateDiscountToDeactive(IdDiscout,user_id);
                }
            } else {
                cenDis = Report.getCenDis(user_id, code);
                if (price > cenDis) {
                    price = price - cenDis;
                    DataManager.insertProduct(IdProduct, IdDiscout, IdOrder, price);
                    DataManager.updateDiscountToDeactive(IdDiscout,user_id);
                }  
            }
        }
            
            JOptionPane.showMessageDialog(null, "New Order was succesfully created", "Warning", JOptionPane.WARNING_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(OrderNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else {
         JOptionPane.showMessageDialog(null, "You dont have any product in shopping bag ", "Warning", JOptionPane.WARNING_MESSAGE);
         }        
        
    }//GEN-LAST:event_jButtonAllActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderNew(DbManager).setVisible(true);
            }
        });
    }
     */
    public void setO(Object[] o) {
        this.o = o;
    }

    public Object[] getO() {
        return o;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAll;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JButton jButtonShow1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabelDiscoutPricce;
    private javax.swing.JLabel jLabelFinalPrice;
    private javax.swing.JLabel jLabelPrice2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMyOrderItem;
    private javax.swing.JTextField jTextDicoutCode;
    private javax.swing.JLabel jlTotalPrice;
    // End of variables declaration//GEN-END:variables
}
