/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Connect.DBManager;
import Controler.Account;
import DML.Inserts;
import DML.UniquePK;
import Model_Object.Company;
import Model_Object.Person;
import Model_Object.UserCompany;
import static com.mysql.jdbc.StringUtils.isNullOrEmpty;
import com.sun.prism.impl.Disposer.Record;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Michal
 */
public class Registration extends javax.swing.JFrame {

    private DBManager DbManager;
    private UserCompany usercompany;

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        this.DbManager = new DBManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButtonFirma = new javax.swing.JRadioButton();
        jRadioButtonOsoba = new javax.swing.JRadioButton();
        jLabelName = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JTextField();
        jLabelCompany = new javax.swing.JLabel();
        jtxtTown = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtCompany = new javax.swing.JTextField();
        jtxtPSC = new javax.swing.JTextField();
        jtxtStreeet = new javax.swing.JTextField();
        jLabelIco = new javax.swing.JLabel();
        jtxtIco = new javax.swing.JTextField();
        buttRegister = new javax.swing.JButton();
        jLabelRC = new javax.swing.JLabel();
        jtxtRC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Registration")));

        jRadioButtonFirma.setText("Firma");
        jRadioButtonFirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFirmaMouseClicked(evt);
            }
        });

        jRadioButtonOsoba.setText("Osoba");
        jRadioButtonOsoba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonOsobaMouseClicked(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelName.setText("Meno: *");

        jLabelSurname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSurname.setText("Priezvisko: *");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Email: *");

        jtxtEmail.setText("kormanak@gmail.com");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Password: *");

        jtxtPassword.setText("aaa");

        jLabelCompany.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCompany.setText("Name of company: *");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Town:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("PSC: *");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Street:");

        jtxtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCompanyActionPerformed(evt);
            }
        });

        jtxtPSC.setText("00001");

        jLabelIco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIco.setText("ICO: *");

        buttRegister.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttRegister.setText("Register");
        buttRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttRegisterActionPerformed(evt);
            }
        });

        jLabelRC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRC.setText("RC: *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIco)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonFirma)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButtonOsoba))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtPSC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtTown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCompany)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(51, 51, 51))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(103, 103, 103)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtName)
                                .addComponent(jtxtSurname)
                                .addComponent(jtxtEmail)
                                .addComponent(jtxtPassword)
                                .addComponent(jtxtCompany)
                                .addComponent(jtxtIco)
                                .addComponent(jtxtRC, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtStreeet, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOsoba)
                    .addComponent(jRadioButtonFirma))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtIco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jtxtTown, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtPSC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtStreeet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(buttRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttRegisterActionPerformed
        String RC = jtxtRC.getText();
        String name = jtxtName.getText();
        String surname = jtxtSurname.getText();
        String company = jtxtCompany.getText();
        String ICO = jtxtIco.getText();
        String PSC = jtxtPSC.getText();
        String email = jtxtEmail.getText();
        String password = jtxtPassword.getText();
        String NameOoTown = jtxtTown.getText();
        String Street = jtxtStreeet.getText();
        UniquePK uniqmethod = new UniquePK(DbManager);
        Inserts DataManager = new Inserts(DbManager);

        if (jRadioButtonFirma.isSelected() == false && jRadioButtonOsoba.isSelected() == false) {
            JOptionPane.showMessageDialog(this,
                    "Aspon jeden s check boxov musi byt zaskrtnuty",
                    "Chyba",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            if (jRadioButtonFirma.isSelected() == true) {
                if (isNullOrEmpty(company)
                        || isNullOrEmpty(ICO)
                        || isNullOrEmpty(PSC)
                        || isNullOrEmpty(password)
                        || isNullOrEmpty(email)) {
                    JOptionPane.showMessageDialog(this,
                            "Vyplňte všetky údaje označené hviezdičkou.",
                            "Chyba",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
                Company compan = new Company(ICO, PSC, company, email);
                UserCompany user = new UserCompany(jRadioButtonFirma.isSelected(), email, Account.hashPassword(password), null, ICO);

                if (uniqmethod.uniqueEmail(email)) {
                    if (uniqmethod.uniqueICO(ICO)) {
                        DataManager.insertCompany(compan);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "ICO " + ICO + " uz niekto pouziva.",
                                "Chyba",
                                JOptionPane.WARNING_MESSAGE);
                    }

                    DataManager.insertUserCompany(user);
                    JOptionPane.showMessageDialog(this, "Úspešné vytvorenie uživateľa  \nlogin: " + email + "\nheslo: " + password);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Email " + email + " uz niekto pouziva.",
                            "Chyba",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
            if (jRadioButtonOsoba.isSelected() == true) {
                if (isNullOrEmpty(PSC)
                        || isNullOrEmpty(RC)
                        || isNullOrEmpty(name)
                        || isNullOrEmpty(password)
                        || isNullOrEmpty(email)
                        || isNullOrEmpty(surname)) {
                    JOptionPane.showMessageDialog(this,
                            "Vyplňte všetky údaje označené hviezdičkou.",
                            "Chyba",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
                Person person = new Person(RC, name, surname, PSC);
                UserCompany user = new UserCompany(false, email, Account.hashPassword(password), RC, null);

                if (uniqmethod.uniqueEmail(email)) {
                    if (uniqmethod.uniqueRC(RC)) {
                        DataManager.insertPerson(person);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Rodne cislo: " + RC + " uz niekto pouziva.",
                                "Chyba",
                                JOptionPane.WARNING_MESSAGE);
                    }

                    DataManager.insertUser(user);
                    JOptionPane.showMessageDialog(this, "Úspešné vytvorenie uživateľa \nlogin: " + email + "\nheslo: " + password);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Email " + email + " uz niekto pouziva.",
                            "Chyba",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    this.dispose();

    }//GEN-LAST:event_buttRegisterActionPerformed

    private void jRadioButtonFirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFirmaMouseClicked
        if (jRadioButtonFirma.isSelected() == true) {
            jLabelCompany.setForeground(new Color(0, 0, 0));
            jLabelIco.setForeground(new Color(0, 0, 0));
            jtxtIco.enable();
            jtxtCompany.enable();
            jRadioButtonOsoba.setSelected(false);
            jtxtName.disable();
            jtxtSurname.disable();
            jtxtRC.disable();
            jLabelName.setForeground(new Color(157, 157, 157));
            jLabelSurname.setForeground(new Color(157, 157, 157));
            jLabelRC.setForeground(new Color(157, 157, 157));
          

        }
    }//GEN-LAST:event_jRadioButtonFirmaMouseClicked

    private void jRadioButtonOsobaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonOsobaMouseClicked
        if (jRadioButtonOsoba.isSelected() == true) {
            jRadioButtonFirma.setSelected(false);
            jLabelName.setForeground(new Color(0, 0, 0));
            jLabelSurname.setForeground(new Color(0, 0, 0));
            jLabelRC.setForeground(new Color(0, 0, 0));
            jtxtName.enable(true);
            jtxtSurname.enable(true);
            jtxtRC.enable(true);
            jtxtIco.disable();
            jtxtCompany.disable();
            jLabelCompany.setForeground(new Color(157, 157, 157));
            jLabelIco.setForeground(new Color(157, 157, 157));
        }
    }//GEN-LAST:event_jRadioButtonOsobaMouseClicked

    private void jtxtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttRegister;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCompany;
    private javax.swing.JLabel jLabelIco;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRC;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFirma;
    private javax.swing.JRadioButton jRadioButtonOsoba;
    private javax.swing.JTextField jtxtCompany;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtIco;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPSC;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtRC;
    private javax.swing.JTextField jtxtStreeet;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTown;
    // End of variables declaration//GEN-END:variables
}
